depot/config/routes.rb
DemoApp::Application.routes.draw do

  resources :orders
  resources :line_items
  resources :carts
  get "store/index"
  resources :products
  get "say/hello"
  get "say/goodbye"
  root  'store#index', :as => 'store'
  get "static_pages/home"

  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/home', to: 'static_pages#home', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'

  resources :users
  
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

end

depot/app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy
  def add_product(product_id)
    current_item = line_items.where(:product_id => product_id).first
    if current_item
    current_item.quantity += 1
    else
      current_item = line_items.build(:product_id => product_id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

depot/app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart
  def total_price
    product.price * quantity
  end
end

depot/app/models/order.rb
class Order < ActiveRecord::Base
  PAYMENT_TYPES = [ "Check", "Credit card", "Purchase order" ]
  validates :name, :address, :email, presence: true
  validates :pay_type, inclusion: PAYMENT_TYPES
  has_many :line_items, dependent: :destroy

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

depot/app/models/product.rb
class Product < ActiveRecord::Base
  
  default_scope :order => 'title'
  validates :title, :description, :image_url, :presence => true
  validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
  validates :title, :uniqueness => true

  validates :image_url, :format => {
            :with => %r{\.(gif|jpg|png$)}i,
            :message => 'must be a URL for GIF, JPG or PNG image.'
}

has_many :line_items

end

depot/app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  after_destroy :ensure_an_admin_remains
  has_secure_password

  private
  def ensure_an_admin_remains
    if User.count.zero?
      raise "Can't delete last user"
    end
  end
end

depot/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  include CurrentCart
  def index
    set_cart
    @total_orders = Order.count
  end
end

depot/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:edit, :update, :destroy]
  skip_before_action :authorize, only: [:create, :update, :destroy]
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show

    begin
      @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_url, :notice => 'Invalid cart'
    else
      respond_to do |format|
        format.html # show.html.erb
        format.xml { render :xml => @cart }
      end
    end
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cart }
      else
        format.html { render action: 'new' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to store_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cart
    @cart = Cart.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cart_params
    params[:cart]
  end
end

depot/app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @time = Time.now
    @saying="Never giving up!"
  end

  def goodbye
  end
end

depot/app/helpers/admin_helper.rb
module AdminHelper
end

depot/app/helpers/application_helper.rb
module ApplicationHelper
  def hidden_div_if(condition, attributes = {}, &block)
    if condition
      attributes["style"] = "display: none"
    end
    content_tag("div", attributes, &block)
  end

end

depot/app/helpers/carts_helper.rb
module CartsHelper
end

depot/app/helpers/line_items_helper.rb
module LineItemsHelper
end

depot/app/helpers/orders_helper.rb
module OrdersHelper
end

depot/app/helpers/products_helper.rb
module ProductsHelper
end

depot/app/helpers/say_helper.rb
module SayHelper
end

depot/app/helpers/sessions_helper.rb
module SessionsHelper
end

depot/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

depot/app/helpers/store_helper.rb
module StoreHelper
end

depot/app/helpers/users_helper.rb
module UsersHelper
end

depot/app/helpers/welcome_helper.rb
module WelcomeHelper
end

depot/app/views/admin/index.html.erb
<h1>Welcome</h1>
It's <%= Time.now %>
We have <%= pluralize(@total_orders, "order") %>.

depot/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Pragprog Books Online Store</title>

		<%= stylesheet_link_tag "scaffold" %>
		<%= stylesheet_link_tag "depot", :media => "all" %>
		<%= javascript_include_tag :application %>
		<%= csrf_meta_tag %>

	</head>

	<body id="store" >
		<div id="banner" >
			<%= image_tag("logo.png") %>
			<%= @page_title || "Pragmatic Bookshelf" %>
		</div>
		<div id="columns" >
			<div id="side" >
				<%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
				<%= render @cart %>
				<% end %>

				<ul>
					<a href="http://www...." >Home</a>
					<br />
					<a href="http://www..../faq" >Questions</a>
					<br />
					<a href="http://www..../news" >News</a>
					<br />
					<a href="http://www..../contact" >Contact</a>
					<br />
				</ul>
				<% if session[:user_id] %>
				<ul>
					<li>
						<%= link_to 'Orders', orders_path %>
					</li>
					<li>
						<%= link_to 'Products', store_path %>
					</li>
					<li>
						<%= link_to 'Users', users_path %>
					</li>
				</ul>
				<%= button_to 'Logout', logout_path, method: :delete %>
				<% end %>
			</div>

			<div id="main" >
				<%= yield %>
			</div>
		</div>
	</body>
</html>

depot/app/views/order_notifier/received.text.erb
Dear <%= @order.name %>
Thank you for your recent order from The Pragmatic Store.
You ordered the following items:
<%= render @order.line_items -%>
We'll send you a separate e-mail when your order ships.

depot/app/views/order_notifier/shipped.text.erb
OrderNotifier#shipped

<%= @greeting %>, find me in app/views/app/views/order_notifier/shipped.text.erb