demo_app/config/routes.rb
DemoApp::Application.routes.draw do
  
  

  resources :orders

  resources :line_items

  resources :carts

  get "store/index"
  resources :products

  get "say/hello"
  get "say/goodbye"
  root  'store#index', :as => 'store'
  get "static_pages/home"

  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/home', to: 'static_pages#home', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  
  

end

demo_app/app/views/layouts/Copy of application_1.html.erb
<!DOCTYPE html>
<html>
  <head>
  	
    <title>Pragprog Books Online Store</title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>    
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    	<% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

demo_app/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", users_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

demo_app/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<nav>
				<ul class="nav pull-right">
					<li>
						<%= link_to "Home", root_path %>
					</li>
					<li>
						<%= link_to "Help", help_path %>
					</li>
					<% if signed_in? %>

					<li>
						<%= link_to "Signed-in:  "+current_user.name, '#' %>
					</li>

					<li>
						<%= link_to "Logout ", signout_path, method: "delete" %>
					</li>

					<% else %>
					<li>
						<%= link_to "Sign in", signin_path %>
					</li>
					<% end %>
				</ul>
			</nav>
		</div>
	</div>

demo_app/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

demo_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Pragprog Books Online Store</title>

		<%= stylesheet_link_tag "scaffold" %>
		<%= stylesheet_link_tag "depot", :media => "all" %>
		<%= javascript_include_tag :application %>
		<%= csrf_meta_tag %>

	</head>

	<body id="store" >
		<div id="banner" >
			<%= image_tag("logo.png") %>
			<%= @page_title || "Pragmatic Bookshelf" %>
		</div>
		<div id="columns" >
			<div id="side" >				
				<%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
				<%= render @cart %>
				<% end %>

				<a href="http://www...." >Home</a>
				<br />
				<a href="http://www..../faq" >Questions</a>
				<br />
				<a href="http://www..../news" >News</a>
				<br />
				<a href="http://www..../contact" >Contact</a>
				<br />
			</div>
			<div id="main" >
				<%= yield %>
			</div>
		</div>
	</body>
</html>